######################################################################
# Automatically generated by qmake (2.01a) ? 11? 25 22:45:57 2015
######################################################################

TEMPLATE = app
TARGET = pdfwidget
DEPENDPATH += .
INCLUDEPATH += . /usr/include/poppler/qt4
CONFIG += qt
QT += gui
LIBS += -lpoppler-qt4

# Input
HEADERS += pdfwidget.h
SOURCES += main.cpp pdfwidget.cpp
